services:
  njs-app1:
    build: 
      context: ./njs-app1
      dockerfile: Dockerfile
    container_name: njs-app1
    ports:
      - "3001:3000"
    volumes:
      - ./njs-app1:/app
    environment:
      - NODE_ENV=development
    restart: always
    networks:
      - webnet
    healthcheck:
      test: ["executable", "arg"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    
  njs-appX:
    build:
      context: ./njs-appX
      dockerfile: Dockerfile
    container_name: njs-appX
    ports:
      - "300X:3000"
    volumes:
      - ./njs-appX:/app
    environment:
      - NODE_ENV=development  
    restart: always
    networks:
      - webnet
    healthcheck:
      test: ["executable", "arg"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    
      
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt

  # Email:    admin@example.com
  # Password: Password: changeme
  # WebUI:    http://localhost:81

networks:
  webnet:
    driver: bridge