services:
  web-breizhrp:
    container_name: breizhrp-njs
    build: ./website-breizhrp
    ports:
      - "3000:3000"
    volumes:
      - ./website-breizhrp:/app
    networks:
      - webnet
      
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/ssl-data:/data/letsencrypt
      - ./certbot:/var/www/certbot
    depends_on:
      - web-breizhrp
    networks:
      - webnet


  certbot:
    image: certbot/certbot
    container_name: certbot
    ports:
      - "82:80"
      - "8843:443"
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $!; done"
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/ssl-data:/data/letsencrypt
      - ./certbot:/var/www/certbot
    networks:
      - webnet

networks:
  webnet:
    driver: bridge